{{- include "adp-helm-library.deployment" (list . "qatester.deployment") -}}
{{- define "qatester.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "adp-helm-library.container" (list . "qatester.container") }}
{{- end -}}
